{
    "name": "Хотын ажиллагаа: Ажилтан ба эрхийн бүртгэл",
    "summary": "Хэрэглэгч, ажилтан, алба нэгж, албан тушаал, системийн эрхийг нэгдсэн байдлаар удирдана.",
    "version": "19.0.1.0.0",
    "category": "Хүний нөөц",
    "author": "OpenAI",
    "license": "LGPL-3",
    "depends": [
        "hr",
        "mail",
        "ops_project_defaults",
        "ops_role_security",
    ],
    "data": [
        "security/ops_people_registry_security.xml",
        "security/ir.model.access.csv",
        "data/access_profile_data.xml",
        "views/access_profile_views.xml",
        "views/migration_run_views.xml",
        "views/people_sync_wizard_views.xml",
        "views/people_import_wizard_views.xml",
        "views/hr_department_views.xml",
        "views/hr_job_views.xml",
        "views/hr_employee_views.xml",
        "views/res_users_views.xml",
        "views/menu_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
