{
    "name": "Албан тушаалын ажлын орон зай",
    "summary": "Албан тушаал бүрт зориулсан эрх, хяналтын самбар, цэс, шуурхай UI",
    "version": "19.0.1.0.0",
    "category": "Services/Project",
    "author": "OpenAI",
    "license": "LGPL-3",
    "depends": [
        "project",
        "hr",
        "fleet",
        "purchase",
        "stock",
        "account",
        "mail",
        "ops_user_type",
        "ops_team_assignment",
        "ops_project_defaults",
        "ops_role_security",
        "ops_field_reporting",
        "municipal_field_ops",
        "municipal_procurement_workflow",
        "fleet_repair_workflow",
        "hr_discipline_transfer_mn",
        "hr_clearance_mn",
        "ops_people_registry",
        "ops_work_unit",
    ],
    "data": [
        "security/municipal_role_groups.xml",
        "security/ir.model.access.csv",
        "security/municipal_role_rules.xml",
        "data/municipal_role_profiles.xml",
        "views/res_users_views.xml",
        "views/municipal_role_dashboard_views.xml",
        "views/municipal_role_menu_views.xml",
        "views/project_project_views.xml",
        "views/project_task_views.xml",
        "views/procurement_request_views.xml",
        "views/fleet_repair_views.xml",
        "views/hr_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "municipal_role_ui/static/src/scss/municipal_role_ui.scss",
        ],
    },
    "installable": True,
    "application": True,
}
