[options]
addons_path = C:\Program Files\Odoo 19.0.20260415\server\odoo\addons,C:\Users\User\Desktop\hot tohjilt\odoo erp\custom_addons
data_dir = C:\Users\User\AppData\Local\OpenERP S.A.\Odoo
db_host = localhost
db_port = 5432
db_user = openpg
db_password = openpgpwd
db_name = odoo19_admin
http_interface = 127.0.0.1
http_port = 8071
gevent_port = 8073
server_wide_modules = base,rpc,web
list_db = True
proxy_mode = False
without_demo = True
log_level = info
logfile = C:\Users\User\Desktop\hot tohjilt\odoo erp\local.odoo.log
